In [1]:
import os
path='/Users/emilito/Documents/PWA/Data/Raw/manning'
os.chdir(path)
os.getcwd()

'c:\\Users\\emilito\\Documents\\PWA\\Data\\Raw\\manning'

In [2]:
import pandas as pd
data = pd.read_csv('upperMC_TP_data.csv')

print(type(data))

data.head(2)

<class 'pandas.core.frame.DataFrame'>

,OBJECTID,DOI,DatasetName,MonitoringLocationID,MonitoringLocationName,MonitoringLocationLatitude,MonitoringLocationLongitude,MonitoringLocationHorizontalCoordinateReferenceSystem,MonitoringLocationHorizontalAccuracyMeasure,MonitoringLocationHorizontalAccuracyUnit,...,ResultStatusID,ResultComment,ResultAnalyticalMethodID,ResultAnalyticalMethodContext,ResultAnalyticalMethodName,AnalysisStartDate,AnalysisStartTime,AnalysisStartTimeZone,LaboratoryName,LaboratorySampleID
0,1,https://doi.org/10.25976/hxqe-py39,Lake Winnipeg Community-Based Monitoring Network,STB_DS2,STEINBACH DOWNSTREAM 2,49.545169,-96.723302,NAD83,NaN,NaN,...,Final,First spring run off sampling. Details on shee...,365.1,USEPA,NaN,NaN,NaN,NaN,"Center for Earth Observation Science, Universi...",NaN
1,2,https://doi.org/10.25976/hxqe-py39,Lake Winnipeg Community-Based Monitoring Network,STB_MSUP,STEINBACH MAINSTEM UPSTREAM,49.551351,-96.642645,NAD83,NaN,NaN,...,Final,"Sampling, for this site. Details in sheet atta...",365.1,USEPA,NaN,NaN,NaN,NaN,"Center for Earth Observation Science, Universi...",NaN

In [3]:
data['ActivityStartDate'] = pd.to_datetime(data['ActivityStartDate'], format='%Y-%m-%d')
data.iloc[:5,:16]

,OBJECTID,DOI,DatasetName,MonitoringLocationID,MonitoringLocationName,MonitoringLocationLatitude,MonitoringLocationLongitude,MonitoringLocationHorizontalCoordinateReferenceSystem,MonitoringLocationHorizontalAccuracyMeasure,MonitoringLocationHorizontalAccuracyUnit,MonitoringLocationVerticalMeasure,MonitoringLocationVerticalUnit,MonitoringLocationType,ActivityType,ActivityMediaName,ActivityStartDate
0,1,https://doi.org/10.25976/hxqe-py39,Lake Winnipeg Community-Based Monitoring Network,STB_DS2,STEINBACH DOWNSTREAM 2,49.545169,-96.723302,NAD83,NaN,NaN,NaN,NaN,River/Stream,Sample-Integrated Vertical Profile,Surface Water,2019-03-27
1,2,https://doi.org/10.25976/hxqe-py39,Lake Winnipeg Community-Based Monitoring Network,STB_MSUP,STEINBACH MAINSTEM UPSTREAM,49.551351,-96.642645,NAD83,NaN,NaN,NaN,NaN,River/Stream,Sample-Integrated Vertical Profile,Surface Water,2019-10-09
2,3,https://doi.org/10.25976/hxqe-py39,Lake Winnipeg Community-Based Monitoring Network,STB_MS1,STEINBACH MAINSTEM,49.574314,-96.772683,NAD83,NaN,NaN,NaN,NaN,River/Stream,Sample-Integrated Vertical Profile,Surface Water,2019-08-13
3,4,https://doi.org/10.25976/hxqe-py39,Lake Winnipeg Community-Based Monitoring Network,STB_DS2,STEINBACH DOWNSTREAM 2,49.545169,-96.723302,NAD83,NaN,NaN,NaN,NaN,River/Stream,Sample-Integrated Vertical Profile,Surface Water,2018-10-17
4,5,https://doi.org/10.25976/hxqe-py39,Lake Winnipeg Community-Based Monitoring Network,STB_MS1,STEINBACH MAINSTEM,49.574314,-96.772683,NAD83,NaN,NaN,NaN,NaN,River/Stream,Sample-Integrated Vertical Profile,Surface Water,2019-05-13

In [4]:
bfr_2021 = (data['ActivityStartDate'] <= '2020-12-31')

bfr_2021 = data.loc[bfr_2021]

num_rows = len(bfr_2021.index)
print(num_rows)

107

In [5]:
spring = data[data['ActivityStartDate'].dt.month.between(2,6)]

num_rows = len(spring.index)
print(num_rows)

103