# Feature Creation Notebook

Authors: Harry Zhang, Thomas Saleh, Elena Milito
Packages authored by: Idil Yaktubay, Amanbir Singh, Harry Zhang, Thomas Saleh 

CODE PURPOSE: Create feature tables for total dissolved solids, turbidity, total organic carbon, and discharge at Pinawa and Whitemouth AquaHive stations, for the purpose of parameter forecasting

## Set-up
Import packages

In [1]:
%load_ext autoreload
%autoreload 2

In [9]:
import pandas as pd
import os
import sys
import feature_creation as fc
sys.path.append('..')

Import ERA5 met timeseries data

In [10]:
full_dataset = pd.read_csv("met_ts_t2m_cdir_CR.csv")

## Generate Timelag features

Cypress River Temperature

In [20]:
t2m_cr_1_12_features = fc.calc_param_site_features_hrs_ago(df=full_dataset, 
                                                        param='t2m',
                                                        site='cr', 
                                                        hours_ago_start=1, 
                                                        hours_ago_end=3)

t2m_cr_13_48_features = fc.calc_param_site_features_hrs_ago(df=full_dataset, 
                                                        param='t2m',
                                                        site='cr', 
                                                        hours_ago_start=4, 
                                                        hours_ago_end=6)

t2m_cr_49_120_features = fc.calc_param_site_features_hrs_ago(df=full_dataset, 
                                                        param='t2m',
                                                        site='cr', 
                                                        hours_ago_start=7, 
                                                        hours_ago_end=9)

t2m_cr_121_720_features = fc.calc_param_site_features_hrs_ago(df=full_dataset, 
                                                        param='t2m',
                                                        site='cr', 
                                                        hours_ago_start=10, 
                                                        hours_ago_end=12)

Combine temperature features from different time windows into a single table

In [21]:
# Create final turbidity concentration feature table (wmth)
t2m_cr_final_features_conc = pd.concat([t2m_cr_1_12_features[0].set_index('timestamp_ccentral'),
                                        t2m_cr_13_48_features[0].set_index('timestamp_ccentral'),
                                        t2m_cr_49_120_features[0].set_index('timestamp_ccentral'),
                                        t2m_cr_121_720_features[0].set_index('timestamp_ccentral')
                                        ],
                                        axis=1)
# Create final turbidity load feature table (wmth)
t2m_cr_final_features_load = pd.concat([t2m_cr_1_12_features[1].set_index('timestamp_ccentral'),
                                          t2m_cr_13_48_features[1].set_index('timestamp_ccentral'),
                                          t2m_cr_49_120_features[1].set_index('timestamp_ccentral'),
                                          t2m_cr_121_720_features[1].set_index('timestamp_ccentral')
                                          ],
                                          axis=1)

Reviewing temperature features dataset

In [22]:
fc.feature_checks(t2m_cr_final_features_conc)
t2m_cr_final_features_conc.head()

columns Index(['t2m_cr_mean_1_3', 't2m_cr_mean_4_6', 't2m_cr_mean_7_9',
       't2m_cr_mean_10_12'],
      dtype='object')
start time 2015-12-31 19:00:00-06:00
end time 2020-12-29 18:00:00-06:00
number of rows 43801 and columns 4.000000
Count of non-null values by column

,t2m_cr_mean_1_3,t2m_cr_mean_4_6,t2m_cr_mean_7_9,t2m_cr_mean_10_12
timestamp_ccentral,,,,
2015-12-31 18:00:00-06:00,NaN,NaN,NaN,NaN
2015-12-31 19:00:00-06:00,NaN,NaN,NaN,NaN
2015-12-31 20:00:00-06:00,NaN,NaN,NaN,NaN
2015-12-31 21:00:00-06:00,265.226898,NaN,NaN,NaN
2015-12-31 22:00:00-06:00,265.785929,NaN,NaN,NaN

In [23]:
# Export datasets as csv (uncomment if need to re-export)
t2m_cr_final_features_conc.to_csv("t2m_cr_concentration_features_test1.csv", index=True)
t2m_cr_final_features_load.to_csv("t2m_cr_load_features_test1.csv", index=True)

Cypress River solar radiation features

In [18]:
cdir_cr_1_12_features = fc.calc_param_site_features_hrs_ago(df=full_dataset, 
                                                        param='cdir',
                                                        site='cr', 
                                                        hours_ago_start=1, 
                                                        hours_ago_end=12)

cdir_cr_13_48_features = fc.calc_param_site_features_hrs_ago(df=full_dataset, 
                                                        param='cdir',
                                                        site='cr', 
                                                        hours_ago_start=13, 
                                                        hours_ago_end=48)

cdir_cr_49_120_features = fc.calc_param_site_features_hrs_ago(df=full_dataset, 
                                                        param='cdir',
                                                        site='cr', 
                                                        hours_ago_start=49, 
                                                        hours_ago_end=120)

cdir_cr_121_720_features = fc.calc_param_site_features_hrs_ago(df=full_dataset, 
                                                        param='cdir',
                                                        site='cr', 
                                                        hours_ago_start=121, 
                                                        hours_ago_end=170)


# Create final turbidity concentration feature table (pnwa)
cdir_cr_final_features_conc = pd.concat([cdir_cr_1_12_features[0].set_index('timestamp_ccentral'),
                                        cdir_cr_13_48_features[0].set_index('timestamp_ccentral'),
                                        cdir_cr_49_120_features[0].set_index('timestamp_ccentral'),
                                        cdir_cr_121_720_features[0].set_index('timestamp_ccentral')
                                        ],
                                        axis=1)

# Create final turbidity load feature table (pnwa)
cdir_cr_final_features_load = pd.concat([cdir_cr_1_12_features[1].set_index('timestamp_ccentral'),
                                        cdir_cr_13_48_features[1].set_index('timestamp_ccentral'),
                                        cdir_cr_49_120_features[1].set_index('timestamp_ccentral'),
                                        cdir_cr_121_720_features[1].set_index('timestamp_ccentral')
                                        ],
                                        axis=1)

# Export datasets as csv (uncomment if need to re-export)
cdir_cr_final_features_conc.to_csv("cdir_cr_concentration_features.csv", index=True)
cdir_cr_final_features_load.to_csv("cdir_cr_load_features.csv", index=True)

Reviewing Cypress River solar radiation dataset

In [19]:
fc.feature_checks(cdir_cr_final_features_conc)
cdir_cr_final_features_conc.head()
#tur_pnwa_final_features_conc.dropna(axis = 0).head()

columns Index(['cdir_cr_mean_1_12', 'cdir_cr_mean_13_48', 'cdir_cr_mean_49_120',
       'cdir_cr_mean_121_170'],
      dtype='object')
start time 2015-12-31 19:00:00-06:00
end time 2020-12-29 18:00:00-06:00
number of rows 43801 and columns 4.000000
Count of non-null values by column

,cdir_cr_mean_1_12,cdir_cr_mean_13_48,cdir_cr_mean_49_120,cdir_cr_mean_121_170
timestamp_ccentral,,,,
2015-12-31 18:00:00-06:00,NaN,NaN,NaN,NaN
2015-12-31 19:00:00-06:00,NaN,NaN,NaN,NaN
2015-12-31 20:00:00-06:00,NaN,NaN,NaN,NaN
2015-12-31 21:00:00-06:00,NaN,NaN,NaN,NaN
2015-12-31 22:00:00-06:00,NaN,NaN,NaN,NaN

## Discharge features
Cypress River

In [12]:
dschrg_cr_1_12_features = fc.calc_discharge_site_features_hrs_ago(df=full_dataset,
                                                        site='cr',
                                                        hours_ago_start=1,
                                                        hours_ago_end=12)
 
dschrg_cr_13_48_features = fc.calc_discharge_site_features_hrs_ago(df=full_dataset,
                                                        site='cr',
                                                        hours_ago_start=13,
                                                        hours_ago_end=48)
 
dschrg_cr_49_120_features = fc.calc_discharge_site_features_hrs_ago(df=full_dataset,
                                                        site='cr',
                                                        hours_ago_start=49,
                                                        hours_ago_end=120)
 
dschrg_cr_121_170_features = fc.calc_discharge_site_features_hrs_ago(df=full_dataset,
                                                        site='cr',
                                                        hours_ago_start=121,
                                                        hours_ago_end=170)
 

# Create final discharge feature table (wmth)
dschrg_cr_final_features = pd.concat([dschrg_cr_1_12_features.set_index('timestamp_ccentral'),
                                        dschrg_cr_13_48_features.set_index('timestamp_ccentral'),
                                        dschrg_cr_49_120_features.set_index('timestamp_ccentral'),
                                        dschrg_cr_121_170_features.set_index('timestamp_ccentral')],
                                          axis=1)

In [15]:
fc.feature_checks(dschrg_cr_final_features)
dschrg_cr_final_features.head()
dschrg_cr_final_features.dropna(axis = 0).head()

columns Index(['dschrg_cr_mean_1_12', 'dschrg_cr_mean_13_48', 'dschrg_cr_mean_49_120',
       'dschrg_cr_mean_121_170'],
      dtype='object')
start time 2015-12-31 19:00:00-06:00
end time 2020-12-29 18:00:00-06:00
number of rows 43801 and columns 4.000000
Count of non-null values by column

,dschrg_cr_mean_1_12,dschrg_cr_mean_13_48,dschrg_cr_mean_49_120,dschrg_cr_mean_121_170
timestamp_ccentral,,,,
2016-01-07 00:00:00-06:00,0.0,0.0,0.0,0.0
2016-01-07 01:00:00-06:00,0.0,0.0,0.0,0.0
2016-01-07 02:00:00-06:00,0.0,0.0,0.0,0.0
2016-01-07 03:00:00-06:00,0.0,0.0,0.0,0.0
2016-01-07 04:00:00-06:00,0.0,0.0,0.0,0.0

In [16]:
# # Export dataset as csv (uncomment if need to re-export)
dschrg_cr_final_features.to_csv("discharge_cr_features_2016-2020.csv", index=True)

## 2. Combine Previous Feature Sets Generated

In [22]:
from src.feature_creation import read_and_merge_csv

#All the toc and tur files
toc_files = [
    'toc_pnwa_concentration_features.csv',
    'toc_pnwa_load_features.csv',
    'toc_wmth_concentration_features.csv',
    'toc_wmth_load_features.csv'
]

tur_files = [
    'tur_pnwa_concentration_features.csv',
    'tur_pnwa_load_features.csv',
    'tur_wmth_concentration_features.csv',
    'tur_wmth_load_features.csv'
]

discharge_files = [
    'discharge_pnwa_features.csv',
    'discharge_wmth_features.csv'
]

#Combine all toc files
toc_combined_df = read_and_merge_csv(toc_files, '../data/interim/')

#Combine all tur files
tur_combined_df = read_and_merge_csv(tur_files, '../data/interim/')

#Combine all dischargefiles
discharge_combined_df = read_and_merge_csv(discharge_files, '../data/interim/')

#Combine the discharge data with toc and tur combined data
toc_merged_df = pd.merge(toc_combined_df, discharge_combined_df, on="timestamp_ccentral", how="outer")
tur_merged_df = pd.merge(tur_combined_df, discharge_combined_df, on="timestamp_ccentral", how="outer")

#Save the combined csv files
toc_merged_df.to_csv(os.path.join(project_conf.PROCESSED_DATA_DIR, '3h_toc_input_features.csv'), index=False)
tur_merged_df.to_csv(os.path.join(project_conf.PROCESSED_DATA_DIR, '3h_tur_input_features.csv'), index=False)

In [23]:

# ## Refer to files:
# ## 1. 3h_toc_input_features.csv
# ## 2. 3h_tur_input_features.csv

# # Glimpse the combined feature sets
# toc_merged_df = pd.read_csv(os.path.join(project_conf.PROCESSED_DATA_DIR, '3h_toc_input_features.csv'))
# tur_merged_df = pd.read_csv(os.path.join(project_conf.PROCESSED_DATA_DIR, '3h_tur_input_features.csv'))

# view_toc.head()
# # view_tur.head()

In [24]:
toc_merged_df.shape

(26831, 91)